_target_: src.core.models.species_detector.SpeciesDetector
in_features: 128
pool_method: max
l1_penalty: 0.1
penalty_multiplier: 1
beta: 0.99
clf_learning_rate: 0.1
label_smoothing: 0.0
attn_learning_rate:
attn_dim:
train_sample_size: 1
eval_sample_size: 1
key_per_target: false
