_target_: src.core.models.species_detector.SpeciesDetector
in_features: 128
pool_method:
l1_penalty: 0.1
penalty_multiplier: 1
beta: 0.0
clf_learning_rate: 0.1
label_smoothing: 0.0
attn_learning_rate:
attn_dim:
attn_weight_decay:
train_sample_size: 1
eval_sample_size: 100
key_per_target: false
training_method:
mean_stage_epochs:
attn_stage_epochs:
final_stage_epochs:
