_target_: src.core.utils.hyperparams.SpeciesDetectorHyperparams
beta: [0.0, 0.99, 0.999]
clf_learning_rate: [1.e-2, 5.e-2, 1.e-1]
l1_penalty: [1.e-3, 2.e-3, 5.e-3, 1.e-2, 5.e-2, 1.e-1]
penalty_multiplier: [1.0]
