 # @package _global_
 # order of defaults determines the order in which configs override each other
defaults:
  - app: default
  - hydra: default
  - paths: default
  - _self_

task_name: default
host: 0.0.0.0
port: 8055
debug: false
