 # @package _global_
 # order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: soundscape_vae_embeddings
  - model: species_detector
  - app: default
  - paths: default

ckpt_path: null
