 # @package _global_
 # order of defaults determines the order in which configs override each other
defaults:
  - data: soundscape_vae_embeddings
  - app: default
  - hydra: default
  - paths: default
  - _self_

task_name: app
