 # @package _global_
 # order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: soundscape_vae_embeddings
  - model: species_detector
  - hyperparams: default
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - hydra: default

task_name: cross_validation

seed: 42
num_workers: 16
num_folds: 7
devices: [0]

launcher:
  n_jobs: 4
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
