 # @package _global_
 # order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: soundscape_vae_embeddings
  - model: species_detector
  - cross_validator: default
  - hyperparams: species_detector
  - callbacks: null
  - logger: null
  - trainer: default
  - paths: default
  - hydra: default

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${task_name}.log
