 # @package _global_
 # order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: soundscape_vae_embeddings
  - model: species_detector
  - cross_validator: default
  - hyperparams: species_detector
  - callbacks: null
  - logger: null
  - trainer: default
  - paths: default
  - hydra: default

seed: 42
num_workers: 16
num_folds: 7
