 # @package _global_
 # order of defaults determines the order in which configs override each other
defaults:
  - data: soundscape_embeddings
  - model: species_detector
  - callbacks: default
  - logger: null
  - trainer: default
  - paths: default
  - hydra: default
  - _self_

task_name: train
tags: ["dev"]
train: True
test: True
ckpt_path: null
seed: null
